# Generated by Django 3.1.3 on 2020-11-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_receita_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
